# Policy class: data
# Attached custom data volumes. Minimal exclusions, standard retention.
IGNORE=(
    ".recycle/"
)
ONE_FILE_SYSTEM="true"
IGNORE_CACHE_DIRS="false"
KEEP_LATEST=10
KEEP_HOURLY=24
KEEP_DAILY=14
KEEP_WEEKLY=8
KEEP_MONTHLY=12
KEEP_ANNUAL=3
COMPRESSION="none"
